### ISSUE TITLE
Using SharpZipLib

### ISSUE THREAD

**Issue by josdion** [Pascal-Krenckel/NppGZipFileViewer#2]
Hi, can you consider replacing GZipStream with [SharpZipLib](https://github.com/icsharpcode/SharpZipLib) or some other compression library that is more robust against corrupted archive files?

**Comment by Pascal-Krenckel** [comment]
If I find the time, since I have to add settings for the compression level to the settings dialog.

**Comment by Pascal-Krenckel** [comment]
There is now a pre-release available that uses SharpZibLib. It also works with BZip2 now.
