### ISSUE TITLE
Does not seem to do anything at all

### ISSUE THREAD

**Issue by snovotill** [Pascal-Krenckel/NppGZipFileViewer#4]
I have notepad++ 8.4.8 on Win11-64 pro.
Upon dropping NppGZipFileViewerX64.dll
into my plugins directory and re-launching
Notepadd++ it does absolutely nothing.
It presents no settings nor any user interface.
Opening a somefile.gz in Notepad++ fails
to decompress the file, displaying the binary.

**Comment by Pascal-Krenckel** [comment]
Hi, did you put the dll in an extra directory?

**Comment by snovotill** [comment]
Hi Pascal and thanks kindly for your response. Yes I put it into a sub-folder and it does seem to quietly load but then not a peep. I tried the X86 version which does cause Notepad++ to complain, so I really don't know what to think. I think your program would be incredibly useful to anyone who works with Linux man-pages "somefile.gz" on Windows, and so it would be superb to see it in the "official Notepad++ plug-ins repository" if you might feel inclined to do that. I'm just learning C++ so it's beyond my ability to troubleshoot the C# code and it's interaction with Notepad++ at this point.

**Comment by Pascal-Krenckel** [comment]
Do the dll and the directory have the same name (without the suffix ".dll")? Npp use the directory name to determine the dll that should be loaded as a plugin, other dlls are ignored.

**Comment by snovotill** [comment]
Yikes! You nailed it Pascal ...instant success, thank you =)
Now I can just WinSCP into my Debian and double-click any .gz to open it directly in Notepad++
Super convenient.

**Comment by Pascal-Krenckel** [comment]
Happy to help
